language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source $PREFER_LOWEST
  
script:
  - phpunit -c tests
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/log/coverage.xml
